// Gating macros for syringe single-tool boot investigation.
// Default all to 0 (disabled) so baseline build approximates upstream behavior.
#pragma once

#ifndef SYRINGE_PATCH_ENTRY_HEARTBEAT
#define SYRINGE_PATCH_ENTRY_HEARTBEAT 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_MODULAR_RELAX
#define SYRINGE_PATCH_BOOTSTRAP_MODULAR_RELAX 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_FP_SHARE
#define SYRINGE_PATCH_BOOTSTRAP_FP_SHARE 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_SELECTIVE_FLASH
#define SYRINGE_PATCH_BOOTSTRAP_SELECTIVE_FLASH 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_DIAG
#define SYRINGE_PATCH_BOOTSTRAP_DIAG 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_FORCE_ACCEPT
#define SYRINGE_PATCH_BOOTSTRAP_FORCE_ACCEPT 0
#endif

#ifndef SYRINGE_PATCH_BOOTSTRAP_SKIP
#define SYRINGE_PATCH_BOOTSTRAP_SKIP 0
#endif

#ifndef SYRINGE_PATCH_SINGLE_TOOL_MINIMAL
#define SYRINGE_PATCH_SINGLE_TOOL_MINIMAL 0
#endif

#ifndef SYRINGE_PATCH_FAULT_LAMP
#define SYRINGE_PATCH_FAULT_LAMP 0
#endif

// Bridge gating macros to existing feature defines (so we avoid invasive source edits):
#if SYRINGE_PATCH_BOOTSTRAP_DIAG && !defined(PUPPY_DIAG_BLINK)
#define PUPPY_DIAG_BLINK
#endif
#if SYRINGE_PATCH_BOOTSTRAP_FORCE_ACCEPT && !defined(PUPPY_FORCE_ACCEPT_AFTER_ATTEMPT)
#define PUPPY_FORCE_ACCEPT_AFTER_ATTEMPT 2
#endif
#if SYRINGE_PATCH_BOOTSTRAP_SKIP && !defined(PUPPY_SKIP_BOOTSTRAP)
#define PUPPY_SKIP_BOOTSTRAP
#endif

#if SYRINGE_PATCH_FAULT_LAMP && !defined(SYRINGE_PATCH_FAULT_LAMP_ACTIVE)
#define SYRINGE_PATCH_FAULT_LAMP_ACTIVE 1
#endif

